export const PORTDATA = [
    {
        name: 'ALLWEB',
        shortDescription: 'React & 유려한 스크롤 효과',
        longDescription:
            '웹사이트 매거진을 주제로 React와 Three.js를 활용하여 유려한 스크롤 효과와 함께 시각적으로 몰입감 있는 인터랙션을 구현하는 데 초점을 맞췄습니다. 임시 데이터를 생성하고 이를 가공하여 동적인 콘텐츠를 효과적으로 배치하는 구조를 설계했습니다.',
        client: 'React 포트폴리오',
        img: '/assets/logo/allweb_logo.webp',
        sizeClass: 'sm-img',
        year: '2024년 12월',
        category: '웹 디자인・개발',
        technologies: ['React'],
        additionalInfo: ['다양한 스크롤 효과'],
        color: '#8d00ff',
        url: 'https://all-web-two.vercel.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/allweb_vd.webm?raw=true',
        how: '개발을 시작할 때 GDWEB을 보며 웹디자인을 즐겁게 고민했습니다. 감각적인 사이트들을 보면서 디자인의 가능성을 탐색했고, 어떻게 하면 더 역동적이고 흥미로운 웹사이트를 만들 수 있을지 고민했습니다. GDWEB이 가진 정적인 느낌을 보완하고 싶어, THREE.JS를 활용해 3D 요소를 추가하며 더욱 생동감 있는 웹사이트를 만들어갔습니다. 단순한 UI를 넘어, 보는 사람에게 몰입감을 줄 수 있는 인터랙티브한 경험을 구현하는 과정이 무척 즐거웠습니다.',
    },
    {
        name: 'colorcolor',
        shortDescription: '색상 조합 추천 서비스',
        longDescription:
            'colorcolor는 트렌디한 색상 팔레트를 좋아요로 저장·공유하며 색상 영감을 얻을 수 있는 컬렉션 플랫폼입니다.',
        client: '포트폴리오',
        img: '/assets/logo/colorcolor_logo.webp',
        sizeClass: 'md-img',
        year: '2025년 3월',
        category: '웹 디자인・개발',
        technologies: ['React', 'Express', 'MySQL'],
        additionalInfo: ['Vercel', 'Render', 'Railway'],
        color: '#0068ff',
        url: 'https://colorcolor.vercel.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/color_vd.webm?raw=true',
        how: 'colorcolor는 트렌디한 색상 조합 컬렉션입니다. 모든 팔레트는 최신 디자인 트렌드를 반영한 감각적인 조합으로 구성되어 있으며, 사용자는 마음에 드는 팔레트에 좋아요를 눌러 쉽게 저장하고 공유할 수 있습니다. colorcolor는 색상의 아름다움을 함께 즐기고, 누구나 쉽게 색상 영감을 받을 수 있는 공간을 제공합니다.',
    },
    {
        name: 'Nicetofonts',
        shortDescription: '폰트 & UI 템플릿',
        longDescription:
            '다양한 폰트 데이터들 중 자신이 원하는 폰트를 선택하여 UI 템플릿에 자신이 선택한 폰트의 자세한 느낌과 특징을 확인할 수 있습니다.',
        client: '포트폴리오',
        img: '/assets/logo/font_logo.webp',
        sizeClass: 'md-img',
        year: '2025년 3월',
        category: '웹 디자인・개발',
        technologies: ['React', 'Express', 'MySQL'],
        additionalInfo: ['Vercel', 'Render', 'Railway'],
        color: '#ff9200',
        url: 'https://nicetofonts.vercel.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/font_vd.webm?raw=true',
        how: '여러 가지 폰트가 존재하는 오늘날, 내가 원하는 폰트를 자유롭게 탐색하고 적용해볼 수 있는 공간이 없다는 아쉬움에서 만들게 되었습니다. 기존의 폰트 관련 웹사이트들은 단순한 미리보기 기능만 제공하는 경우가 많아, 실제로 폰트를 다운로드한 후에야 자세한 특징을 확인할 수밖에 없는 불편함이 있었습니다. 다양한 UI 템플릿을 통해 자유롭게 폰트를 체험하는 공간을 만들고자 했습니다. ',
    },
    {
        name: 'InterviewAi',
        shortDescription: 'OpenAi를 활용한 모의면접 & 로그인',
        longDescription:
            '면접 준비를 위한 AI 기반 인터뷰 시뮬레이션 서비스입니다. 사용자는 원하는 직무를 선택한 후, 제공된 면접 질문에 답변하면 OpenAI가 답변을 분석하고 평가 점수를 시각적으로 제공하며, 최신 직무 관련 뉴스도 함께 제공합니다.',
        client: '포트폴리오',
        img: '/assets/logo/interview_logo.webp',
        sizeClass: 'md-img',
        year: '2025년 2월',
        category: '웹 디자인・개발',
        technologies: ['React', 'Express', 'MySQL'],
        additionalInfo: ['OpenAI', 'JWT', 'Vercel', 'Render', 'Railway'],
        color: '#e04000',
        url: 'https://interview-ai-omega.vercel.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/interview_vd.webm?raw=true',
        how: 'AI가 대세가 된 지금, AI와 관련된 간단한 서비스를 만들어보고 싶었습니다. 개발자는 현재 가지고 있는 문제를 개발 지식을 통해 해결하는 사람이라고 생각했고, 그렇다면 나에게 필요한 것은 무엇일까 고민하기 시작했습니다. 고민끝에 직무를 입력하면 질문을 만들어주는 간단한 Ai 서비스를 만들 수 있었습니다.',
    },
    {
        name: 'CollabLive',
        shortDescription: 'React + Express + WebRTC',
        longDescription:
            '실시간 화면 공유 및 채팅 애플리케이션으로, 사용자가 URL을 통해 간편하게 접속하여 화면을 공유하고 채팅으로 소통할 수 있도록 설계되었습니다. Express를 사용해 서버를 처음 구축하고, Render를 활용하여 배포했으며, WebRTC를 통해 실시간으로 원활한 화면 공유 기능을 구현했습니다.',
        client: 'React + Express + WebRTC',
        img: '/assets/logo/collab_logo.webp',
        sizeClass: 'md-img',
        year: '2025년 1월',
        category: '웹 디자인・개발',
        technologies: ['React', 'Express', 'WebRTC'],
        additionalInfo: ['Vercel', 'Render'],
        color: '#2669ff',
        url: 'https://drawapp-five.vercel.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/collab_vd.webm?raw=true',
        how: '좋아하는 유튜버의 실시간 라이브 방송을 보면서, 실시간으로 소통할 수 있는 웹 애플리케이션을 만들고 싶다는 생각이 들었습니다. 단순히 영상을 시청하는 것을 넘어, 시청자들이 함께 참여하고 소통하는 경험을 웹에서 구현해보고 싶었습니다. 단순한 아이디어가 기능으로 구현되는 과정이 신기했고,  더 다양한 방식으로 아이디어를 발전시켜보고 싶다는 생각이 들었습니다.',
    },

    {
        name: 'WithUs',
        shortDescription: '공공데이터 활용 & Google Maps',
        longDescription:
            '공공데이터를 활용해 사용자에게 사고 다발 지역, 전국 날씨, 미세먼지 경보 데이터를 시각적으로 제공하며, 해당 정보를 Google Maps를 활용해 데이터를 직관적으로 확인할 수 있도록 구현했습니다.',
        client: 'React + API 포트폴리오',
        img: '/assets/logo/withus_logo.webp',
        sizeClass: 'lg-img',
        year: '2025년 1월',
        category: '웹 디자인・개발',
        technologies: ['React', 'API'],
        additionalInfo: ['공공데이터 활용', 'Vercel'],
        color: '#00a2ff',
        url: 'https://weather-map-one.vercel.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/withus_vd.webm?raw=true',
        how: '다양한 데이터를 다뤄보고 싶다는 생각이 들어 데이터를 가져와 시각화해봤습니다. 시간과 날씨 변화에 따라 실시간으로 업데이트하면서, 화면이 동적으로 변하는 모습을 보는 게 무척 신기했습니다. 특히, 변화하는 데이터를 어떻게 시각적으로 표현할지 고민하면서 디자인과 기능을 조화롭게 구성하는 법을 배울 수 있었습니다. 코드 한 줄로 현실의 변화를 담아낼 수 있다는 점이, 개발의 매력을 다시 한번 느끼게 해준 순간이었습니다.',
    },
    {
        name: 'A4 패키지(웹디자인)',
        shortDescription: '웹 디자인 & 피그마',
        longDescription:
            ' 클라이언트의 브랜드 정체성과 제품 특성을 반영한 깔끔한 디자인을 선택하여, 직관적인 레이아웃을 구현하는 데 초점을 맞췄습니다. 기업의 신뢰감을 강조하는 깔끔한 레이아웃과 친환경적인 브랜드 이미지를 시각적으로 표현하였습니다.',
        client: '에이포 패키지',
        img: '/assets/logo/a4_logo.webp',
        sizeClass: 'lg-img',
        year: '2024년 11월',
        category: '웹 디자인',
        technologies: ['Figma'],
        additionalInfo: ['해당없음'],
        color: '#000',
        url: 'https://a4-custom.web.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/a4_vd.webm?raw=true',
        how: '운 좋게 프리랜서로 웹디자인 외주를 맡게 되었습니다. 피그마를 활용해 디자인 작업을 진행했습니다. 고객과 소통하며 요구사항을 듣고, 피드백을 반영하는 과정을 거치면서 실전 경험을 쌓을 수 있었습니다. 단순한 디자인 작업을 넘어, 사용자와 클라이언트의 니즈를 균형 있게 조율하는 법을 배운 의미 있는 시간이었습니다.',
    },
    {
        name: '티에이 프로젝트',
        shortDescription: '첫 번째 실전 프로젝트 & 향상된 사용자 효과',
        longDescription:
            '브랜드의 정체성을 강조하는 감각적인 디자인과 다양한 스크롤 효과를 적용하여 몰입감을 높였습니다. 인터랙티브한 요소와 가로 스크롤을 활용했으며, 사용자가 콘텐츠를 자연스럽게 탐색할 수 있도록 구성했습니다. 또한, 고객과의 원활한 소통을 위해 이메일 문의 접수 기능을 추가하여 사용자가 웹사이트 내에서 간편하게 문의 사항을 보낼 수 있도록 했습니다.',
        client: '티에이 프로젝트',
        img: '/assets/logo/trable_logo.webp',
        sizeClass: 'lg-img',
        year: '2024년 6월',
        category: '웹 디자인・개발',
        technologies: ['HTML', 'CSS', 'JavaScript'],
        additionalInfo: ['다양한 스크롤 효과'],
        color: '#0b345f',
        url: 'https://trablehomepage.vercel.app/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/ta_vd.webm?raw=true',
        how: '취업 후, 회사 홈페이지 제작을 맡게 되었습니다. 다양한 분야에서 사업을 전개하는 만큼, 각 분야의 개성이 돋보이도록 페이지를 구성하는 것이 중요했습니다. 사용자가 자연스럽게 흐름을 따라가며 회사의 비전과 강점을 직관적으로 느낄 수 있도록, 디자인과 UX/UI에도 신경을 기울였습니다.',
    },
    {
        name: 'HEY 패션 플랫폼',
        shortDescription: '다채로운 인터랙션과 스크롤 효과',
        longDescription:
            '다채로운 인터랙션과 다양한 스크롤 효과를 활용하여 세련된 사용자 경험을 제공하는 데 중점을 두었습니다. 패션 매거진 특유의 감각적인 비주얼을 강조하기 위해 가로 스크롤을 적용했습니다. 페이지 전환과 콘텐츠 노출 방식에 변화를 주어 사용자가 자연스럽게 콘텐츠에 몰입할 수 있도록 설계했습니다.',
        client: '개인 2차 포트폴리오',
        img: '/assets/logo/hey_logo.webp',
        sizeClass: 'sm-img',
        year: '2024년 1월',
        category: '웹 디자인・개발',
        technologies: ['HTML', 'CSS', 'JavaScript'],
        additionalInfo: ['다양한 스크롤 효과'],
        color: '#740001',
        url: 'http://dongbinhosting.dothome.co.kr/main/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/hey_vd.webm?raw=true',
        how: '패션을 좋아해 패션을 다루는 웹사이트를 만들어보고 싶었습니다. 감각적인 비주얼과 트렌디한 분위기를 담아내고 싶었습니다. 레이아웃과 인터랙션 등 동적인 느낌이 살아나도록 고민하며 작업했습니다. 패션이 주는 에너지를 화면에서도 그대로 느낄 수 있도록, 보는 순간 매력적으로 다가오는 사이트를 만드는 게 목표였습니다.',
    },
    {
        name: 'TEAMC',
        shortDescription: '반응형 & 팀프로젝트',
        longDescription:
            '다양한 디바이스에서 최적화된 UI를 제공하기 위해 반응형 구조를 적용했습니다. 스크롤 애니메이션을 활용하여 부드러운 페이지 전환 효과를 추가하고, 드래그 기능을 구현하여 직관적인 UX를 제공했습니다. 팀원 간 역할을 분배하여 협업하며 개발을 진행했습니다.',
        client: '팀플레이',
        img: '/assets/logo/teamc_logo.webp',
        sizeClass: 'sm-img',
        year: '2023년',
        category: '웹 디자인・개발',
        technologies: ['HTML', 'CSS', 'JavaScript', 'jQuery'],
        additionalInfo: ['스크롤 효과 및 드래그 기능'],
        color: '#8300ff',
        url: 'http://teamc.dothome.co.kr/main/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/teamc.webm?raw=true',
        how: '첫 번째 팀프로젝트로, 팀장을 맡아 팀원들의 코드를 종합하는 역할을 했습니다. 각자의 코드가 하나의 흐름으로 이어지도록 조율하는 과정이 쉽지만은 않았지만, 그만큼 배운 것도 많았습니다. 특히 반응형 디자인에 집중하며, 어떤 환경에서도 매끄럽게 보이는 화면을 만드는 데 많은 시간을 들였습니다.',
    },
    {
        name: '#PLAYGAME',
        shortDescription: '동적 애니메이션과 향상된 사용자 경험',
        longDescription:
            '키프레임 및 플러그인 적용을 통해 동적인 애니메이션 효과와 사용자 경험을 향상시키는 요소들이 포함되었습니다. jQuery를 활용하여 웹사이트의 다양한 인터랙션을 구현했으며, 부드럽고 자연스러운 동작을 연출하였습니다.',
        client: '개인 1차 포트폴리오',
        img: '/assets/logo/playgame_logo.webp',
        sizeClass: 'sm-img',
        year: '2023년',
        category: '웹 디자인・개발',
        technologies: ['HTML', 'CSS', 'jQuery'],
        additionalInfo: ['키프레임 및 플러그인 적용'],
        color: '#0059ff',
        url: 'http://teamc.dothome.co.kr/first_port/',
        webVd: 'https://github.com/dongbinkoo/PORTWEBP/blob/main/playgame_vd.webm?raw=true',
        how: '디자인도, 개발도 아무것도 몰랐던 23년 여름. 단순한 호기심이 코드 한 줄, 화면 한 페이지로 이어지며 어느새 나만의 첫 번째 포트폴리오 웹사이트가 되었습니다. 모든 것이 낯설고 어렵게만 보였지만, 하나씩 배워가며 조각들을 맞춰나가는 과정에 대한 기대감이 있었습니다.',
    },
];
